### ISSUE TITLE
KEY_TOUCH triggering randomly on New 3ds in dsi mode

### ISSUE THREAD

**Issue by Drenn1** [devkitPro/libnds#15]
KEY_TOUCH is triggering randomly in DSi mode on my New 3DS, but not on my regular 3DS.

Commit https://github.com/devkitPro/libnds/commit/bed2e2aa9b59b410c6a6b390319ba7cf4f454de3 sounds as if it should solve the problem, but it doesn't.

**Comment by fincs** [comment]
On my (Non-XL) New 3DS, touch screen in DSi mode did not work at all until that change was made.

**Comment by Drenn1** [comment]
Mine is XL. My homebrew only uses the touch screen to open the menu if it's touched. Maybe the coordinates themselves are correct, but I'm not checking them.

**Comment by WinterMute** [comment]
Triggering randomly how? Can you provide (small) source which illustrates the issue?

**Comment by WinterMute** [comment]
Closing for lack of information.

**Comment by Drenn1** [comment]
lol, sorry. Here's the project you wanted. All it does is print the value of "keysCurrent()". When installed as a CIA, you'll see the "touch" input randomly flickering.

https://github.com/Drenn1/n3ds-bug-demo

**Comment by Drenn1** [comment]
Also, I'm not sure where to mention this, but the "examples" page at libnds.devkitpro.org seems to be broken. The examples are all blank pages.

**Comment by ahezard** [comment]
Great issue handling here!
Fixing https://github.com/devkitPro/libnds/issues/23 and setting bit 24 on the 0x1BC cia for 3ds/new3ds would fix this.

**Comment by WinterMute** [comment]
try these.

I've tested both files on my N3DS and see no random flickering. I've used both nds-hb-menu & dslink to boot the nds & installed the cia via FBI.
 
[n3ds-bug-demo.zip](https://github.com/devkitPro/libnds/files/785493/n3ds-bug-demo.zip)

**Comment by Drenn1** [comment]
The cia in that zip still produces the same issue. It doesn't respond to the touch input - the digit corresponding to that input just flickers between 0 and 1. I also used fbi to install it.

fwiw I'm using an american new 3ds XL.

**Comment by WinterMute** [comment]
What firmware are you running?

**Comment by Drenn1** [comment]
11.2.0-35U.

**Comment by WinterMute** [comment]
What CFW setup are you using? Have you calibrated the touchscreen?

I take it you're not having touchscreen issues with official DSiWare or DSi enhanced gamecards?

**Comment by Drenn1** [comment]
The touchscreen appears to work correctly in good old Boxlife.

I got this 3ds recently, and it was calibrated in the initial setup. I just calibrated it again for good measure, no change.

I use Luma with a9lh. I was using an hourly build of Luma. I've tried reverting to 6.6, and I've tried the latest hourly (https://github.com/AuroraWright/Luma3DS/commit/5f8a61201b6e0774236cc2cb09e920c0fcdaa5a9), but there's no change.

**Comment by al3x10m** [comment]
i bet hardware fault...noise on touch maybe..loose ribbon?

**Comment by Drenn1** [comment]
I guess I can't rule out a hardware fault, but it seems very specific. The touchscreen works just fine for everything I've tried except dsi-mode homebrew. Even regular ds-mode is fine.

Anyway, I've opened an o3ds before... never again.

**Comment by Drenn1** [comment]
I've modified the test project to print where it detects being touched. It always reports "232,175" as the touched position.

**Comment by fincs** [comment]
@Drenn1 are you still here? We are working on fixing the touch screen code. Can you test this?
[touch_test2.zip](https://github.com/devkitPro/libnds/files/1290142/touch_test2.zip)

**Comment by Drenn1** [comment]
I feel like I'm experiencing a heisenbug. It works, but now the old version that Wintermute linked does too. Tried recompiling with commit 4fd3a9f1ca65ba11e8199790e14471fe243ec95b, and it still seems to be working. Maybe the problem wasn't in libnds, exactly. No idea.

**Comment by WinterMute** [comment]
@Drenn1 yeah, that's kind of expected. We've added init code that will  tend to get binaries lacking the init code to work - sometimes.

Just make sure you use the latest arm7 code for combined projects & you should be golden

https://github.com/devkitPro/nds-examples/blob/master/templates/combined/arm7/source/template.c#L64
