### ISSUE TITLE
Access to sdmmc sdcard device from arm7 is not working

### ISSUE THREAD

**Issue by ahezard** [devkitPro/libnds#21]
These 2 functions are defined into include/nds/arm7/sdmmc.h but not implemented anywhere :
int sdmmc_sdcard_readsectors(u32 sector_no, u32 numsectors, void *out);
int sdmmc_sdcard_writesectors(u32 sector_no, u32 numsectors, void *in);

**Comment by WinterMute** [comment]
FWIW, you shouldn't be using the arm7 functions directly if at all possible. 

Be very, very careful how you approach use of DSi specific hardware.

**Comment by ahezard** [comment]
I need it for nds-bootstrap. I know that I need to be careful, specially with the nand device.

Can you add an implementation for this functions?
