### ISSUE TITLE
Better detection of the touchscreen controller mode

### ISSUE THREAD

**Issue by ahezard** [devkitPro/libnds#23]
If libnds detect some dsi SCFGs registers available it switch immediately the touchscreen handling code to TWL controller mode. This is not how the hardware works.  The mode of controller is not linked to any SCFGs registers values so this code is wrong. The touchscreen controller mode is an independent feature controlled by the bit 24 of the 0x1BC srl or cia. There is no known way to switch it at runtime.
All others dsi features including new bios can be switched at runtime provided the application have an unlocked access to SCFGs regiters on arm7 and arm9 (given by bit 31 of 0x1B8 registers = 1).

It should be possible to detect the current mode used by analyzing the response to some SPI commands. It is only needed to determine that once since it cannot be changed afterwards.

**Comment by fincs** [comment]
libnds is only meant to work in proper TWL mode, and we are definitely not going to support hybrid frankenstein modes. The proper way to deal with this involves manually switch the TSC into NTR mode just before transferring control to legacy NDS-only software (and likewise, SCFG should be configured to NTR mode and locked down). IIRC, Martin Korth [has an idea](http://devkitpro.org/viewtopic.php?p=15729#p15729) of what might be the actual way to perform the switch, however he hasn't published it in gbatek. You may be better off trying to contact him.

**Comment by ahezard** [comment]
Well this is your choice. So I will maintain my fork of libnds until a better fix is found. This issue prevents Nitrohax UI to works properly on 3ds (or you ahve the UI working properly but you break games). There is just no other way to do it now than to force libnds to use the NTR controller touchscreen code.

Thanks for the link I will contact Martin Korth.
