### ISSUE TITLE
about AES

### ISSUE THREAD

**Issue by Jimmy-Z** [devkitPro/libnds#26]
Is there any plans to expose DSi AES? I don't know any ARM ASM so I'll have to rely on libnds to provide this.

I need this for a better fwTool as in https://github.com/WinterMute/fwTool/issues/1, of cause a C implementation could be easily ported to DS, it's alright for some small checks like https://github.com/Jimmy-Z/TWLbf/blob/master/sector0.c, but performance might suck for fsck.

**Comment by WinterMute** [comment]
Yes. 

Like I said over there it's going to be better to wait until libnds updates are released and fwTool is updated before submitting PRs

**Comment by Jimmy-Z** [comment]
Thanks.
