### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by FrankHB** [devkitPro/libnds#3]
The code in headers can make the compiler complain a lot when specified some warning options, e.g. `-Wpacked`, `-Wsign-conversion`, also `-Wpedantic`(due to redundant semicolons, etc). This is annoying for users who want to enable these options to check their code.
Perhaps the simplest fix is adding `#pragma GCC system_header` for each header.

**Comment by WinterMute** [comment]
you can also use -isystem for these files.

Do you want this done in templates?
