### ISSUE TITLE
Can we have socket library stuff stored inside of libsocket.a as well?

### ISSUE THREAD

**Issue by TheElementalOfCreation** [devkitPro/libnds#35]
I am trying to modify a program to work on the ds, but I keep running into problems. The biggest problem is that it requires makefile configuration through a ./configure file. While most of the errors I can fix by simply making some small changes to the source code of the program, one thing I can't figure out how to fix is that it is specifically looking for socket functions inside of `libsocket.a`, a library that does not exist as all of the socket stuff is in `libdswifi9.a`.

Any help would be appreciated. Thanks.

**Comment by fincs** [comment]
Huh?

There are no shared libraries on DS. `dswifi9.so` does not exist either.

**Comment by TheElementalOfCreation** [comment]
*facepalm* Wow I'm tried. Meant to put all of those as .a let me fix that.

**Comment by fincs** [comment]
What are you trying to build? I don't recall there ever being a `-lsocket` library containing socket functions.

**Comment by TheElementalOfCreation** [comment]
I'm working on trying to port several languages. So far I've had success porting Lua (although I'm not entirely done with that am will still need to do A LOT more testing to make sure all of the basic stuff is working properly). The one I'm currently working on is TCL, which if I tell it to sort of forget completely about the socket code will almost entirely compile (it still tries to link to -lsocket and fails at this step).

**Comment by WinterMute** [comment]
There isn't enough information here to provide a meaningful response. Will close soon without further clarification.
