### ISSUE TITLE
getHeapLimit() and ARM7 binary entrypoint

### ISSUE THREAD

**Issue by amg98** [devkitPro/libnds#37]
While testing, I encountered that the address returned by getHeapLimit() is greater than the default ARM7 binary entrypoint, then I assume that malloc() calls will overlap it when RAM is almost fully used.

**Comment by fincs** [comment]
Default ARM7 entrypoint is in main RAM due to reasons having to do with official firmware loading code, however ARM7 relocates itself to the arm7 wram area during startup. There isn't really any issue.
