### ISSUE TITLE
About `std::chrono` clocks

### ISSUE THREAD

**Issue by FrankHB** [devkitPro/libnds#4]
It seems that `std::chrono::system_clock::now()`, `std::chrono::steady_clock::now()` and `std::chrono::high_resolution_clock::now()` do not work.

Current libstdc++ is configured with `_GLIBCXX_USE_GETTIMEOFDAY`, which uses `gettimeofday` for this. However, the precision is too low.

To make it work effectively, custom implementation with timers should be used.

The function `gettimeofday` is not quite fit for this purpose. It is also obsolescent in POSIX.

I cannot find where to override, even if `clock_gettime` can be used for libstdc++.

So I propose that:
- Setting `_GLIBCXX_USE_CLOCK_REALTIME` instead of `_GLIBCXX_USE_GETTIMEOFDAY`.
- Allowing user to implement `clock_gettime`, this can be achieved by:
  - Providing a stub of `clock_gettime` (with `__attribute__((weak))`).
  - Providing a system call entry to allow the user override at runtime is also good.

Alternatively, patch `libstdc++-v3/src/c++11/chrono.cc` in current libstdc++ source to use custom implementation. This seems to be most efficient since it can avoid unnecessary 10^n multiplication required by `clock_gettime` or `gettimeofday` results.

**Comment by WinterMute** [comment]
With latest tools you can set custom functions for the clock_ calls.

    #include <sys/iosupport.h>
    
    int my_clock_getres(clockid_t clock_id, struct timespec *tp) {
        ...
    }
    
    int my_clock_gettime(clockid_t clock_id, struct timespec *tp) {
        ...
    }
    
    int my_clock_settime(clockid_t clock_id,const struct timespec *tp) {
        ...
    }
    
    __syscalls.clock_gettime = my clock_gettime;
    __syscalls.clock_getres = my_clock_getres;
    __syscalls.clock_settime = my_clock_settime;
