### ISSUE TITLE
Link to forum doesn't work

### ISSUE THREAD

**Issue by NightYoshi370** [devkitPro/libnds#42]
Right next to the description of the GitHub repository, there is a URL. The URL gives me a 404 error: http://devkitpro.org/viewforum.php?f=6

**Comment by WinterMute** [comment]
Sorry. We did a bit of rearranging a while ago and neglected to update links here. Fixed now.

**Comment by NightYoshi370** [comment]
Thank you WinterMute. I thought it was a link to a specific forum just about libnds development which then got privated. I wasn't sure whether it was the DS/DSi Development forum.
