### ISSUE TITLE
FIFO sync is broken when loading from flashcart

### ISSUE THREAD

**Issue by tilderain** [devkitPro/libnds#47]
Using M3DS Real, for instance basic_sound's mod playback runs, but its ambulance and boom noises don't work. Other sound fifo is also affected.
(however, it works fine when using a compatible hbmenu, and on emulators)

I tracked it down to this commit: https://github.com/devkitPro/libnds/commit/5e320f9cba63523064c0fa95e91da9afec72ac44

**Comment by kellda** [comment]
I seem to have to same problem here, tracked down to the same commit… I'm also using a M3i zero with M3DS Real. In my case, the X and Y keys (and the touchscreen) doesn't work, or only work during the first 0.5 seconds after I started the game.

**Comment by WinterMute** [comment]
M3DS Real kernel is kind of broken, would suggest using the wood M3 kernel instead.


[m3dsreal-wood-hbmenu-0.9.0.zip](https://github.com/devkitPro/libnds/files/13464680/m3dsreal-wood-hbmenu-0.9.0.zip)
