### ISSUE TITLE
Please make a release!

### ISSUE THREAD

**Issue by ds-sloth** [devkitPro/libnds#60]
Thanks for your hard work on this project. I'm finding that #52 is substantially improving rendering in my application (which needs to make on-the-fly texture loads because it involves a very large number of textures, only a small proportion of which are onscreen at any given point). It would be great to have this patch available straight from the pacman package instead of needing the user to build and install from source. Thanks for your consideration!

**Comment by WinterMute** [comment]
Sorry. We have some bigger changes in progress & were delaying while we get those ready. Lacking the necessary circular tuit for the other changes I've released 1.8.3 with #52 included.

**Comment by ds-sloth** [comment]
Thank you!
