### ISSUE TITLE
LOAD error: .fini_array can't be allocated in segment 8

### ISSUE THREAD

**Issue by Lorenzooone** [devkitPro/libnds#61]
### What's the issue you encountered?

When using libnds2, sometimes (not always. Often just adding/removing a line of code removes this) compilation prints out the following warning/error:
```
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /<path_to_src>/Pokemon-Trade-Gen3-to-Gen-12.elf: section `.fini_array' can't be allocated in segment 8
LOAD: .main .iwram.__aeabi_uidivmod .main.rw .eh_frame .tinfo .init_array .fini_array
```

Compilations completes just fine and I can see no crashes, but it's weird.

### How can the issue be reproduced?

https://github.com/Lorenzooone/Pokemon-Gen3-to-Gen-X use "make -f Makefile.arm9libnds2".
Do note that the Agbabi library is required, as well as setting the environment variable LIBAGBABI to its path.

### Environment?
OS: Ubuntu 22.04.4 LTS

### Additional context?

**Comment by WinterMute** [comment]
The Agbabi library isn't something we support, sorry.
