### ISSUE TITLE
Release 2.0.0 broke display on both emulators (DeSmuME, melonDS, no$GBA) and real hardware (DS Lite)

### ISSUE THREAD

**Issue by Chi-Iroh** [devkitPro/libnds#62]
### What's the issue you encountered?

I updated `libnds` to the `2.0.0-6` version using `pacman`, and noticed it broke the display.  
I compiled [a game I made earlier](https://github.com/Chi-Iroh/Pong-NDS/commit/1ed1e107615b9faa8dcb3648d4510f41054524aa) again after the update, and launched it with DeSmuME (0.19.3-1), melonDS (0.9.5-6) and no$GBA (with wine 9.20-1) on my x86_64 ArchLinux, and they all only displayed two white screens.

Then I tried launching the game on real hardware (DS Lite), and only backgrounds are displayed, not sprites.

### How can the issue be reproduced?

[This libnds commit](https://github.com/devkitPro/libnds/commit/6cfbd4494d94a16982b8e7cefb7c63155a3d894b) was fine, my game worked well with it.
You can compile my game using the above link (`make` command is enough), and run it.
I also found that debugging with `iprintf` seems to work correctly, you can try with this assembly file :
```assembly
    .section .text
    .global main

main:
    push {lr}
    bl consoleDemoInit
    ldr r0, =msg
    mov r1, #42
    mov r2, #24
    bl iprintf

loop_forever:
    b loop_forever
    pop {pc}

    .section .rodata
msg:
    .asciz "Hello World! Values: %d and %d\n"
```
It displays white screens on the aforementioned emulators, but works as expected on my DS Lite.

### Environment?

As said before, I use Arch Linux x86_64, my `uname -a` : `Linux hostname 6.11.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Nov 2024 17:57:56 +0000 x86_64 GNU/Linux`.  
Here are my devkitpro environment variables : 
```
DEVKITARM=/opt/devkitpro/devkitARM
DEVKITPPC=/opt/devkitpro/devkitPPC
DEVKITPRO=/opt/devkitpro
```
I only use official binaries from pacman, and I didn't modify my devkitpro installation.

Also, I tried to downgrade libnds with `downgrade libnds`, but the command could only find `2.0.0-6` version.

If some relevant information is missing, please tell me and I'll update my issue.
Anyway, thanks for all your amazing work !

**Comment by fincs** [comment]
libnds v2 and calico have been tested on real hardware, no$gba and melonDS [(with appropriate patching)](https://github.com/melonDS-emu/melonDS/pull/2197). Can you try compiling a [normal example from nds-examples](https://github.com/devkitPro/nds-examples/tree/master/templates/arm9)?

**Comment by Chi-Iroh** [comment]
I compiled it (using the very same Makefile from the link you provided), and I got 2 white screens on DesMuME and melonDS, but works as expected on my DS Lite.

**Comment by Chi-Iroh** [comment]
The 'appropriate patching' works as expected, I just compiled melonDS with your changes and it runs well.

**Comment by fincs** [comment]
You may also want to review the [summary of major changes in libnds v2](https://devkitpro.org/viewtopic.php?f=13&t=9662#p18269) for things that require attention ("Quick porting checklist"). Something not mentioned in the list is that you now need to explicitly configure all VRAM banks (i.e. there is no default VRAM configuration anymore). If you have any further support questions, [don't hesitate to ask in the devkitPro forums](https://devkitpro.org/viewforum.php?f=38).

**Comment by Chi-Iroh** [comment]
I couldn't reproduce the bug I had on real hardware with my game (where only backgrounds were displayed), everything is fine on both the patched melonDS and my DS Lite.
