### ISSUE TITLE
Wifi is broken in DSi mode

### ISSUE THREAD

**Issue by ghost** [devkitPro/libnds#8]
None of the 3 wifi examples work under sudokuhax on DSi or 3DS. Homebrew that uses wifi functions are broken too. The init functions return errors.

**Comment by fincs** [comment]
This is a known issue - a driver for the DSi Wifi chip hasn't been written/ported yet.

**Comment by idgrepthat** [comment]
Ok thanks for responding.

**Comment by WinterMute** [comment]
We eventually found a way to get the newer wifi boards to run DS mode wifi.
